from cryptofeed_worker import OrderBook


class MasterObject:

    def __init__(self):
        self.inchBookObject = OrderBook('1inch',
                                        '1INCH-USD',
                                        '1INCH',
                                        '1INCH-USD Live Chart'),
        self.quickBookObject = OrderBook('quick',
                                         'QUICK-USD',
                                         'QUICK',
                                         'QUICK-USD Live Chart'),
        self.qntBookObject = OrderBook('qnt',
                                       'QNT-USD',
                                       'QNT',
                                       'QNT-USD Live Chart'),
        self.zrxBookObject = OrderBook('zrx',
                                       'ZRX-USD',
                                       'ZRX',
                                       'ZRX-USD Live Chart'),
        self.eosBookObject = OrderBook('eos',
                                       'EOS-USD',
                                       'EOS',
                                       'EOS-USD Live Chart'),
        self.axsBookObject = OrderBook('axs',
                                       'AXS-USD',
                                       'AXS',
                                       'AXS-USD Live Chart'),
        self.xtzBookObject = OrderBook('xtz',
                                       'XTZ-USD',
                                       'XTZ',
                                       'XTZ-USD Live Chart'),
        self.ethBookObject = OrderBook('eth',
                                       'ETH-USD',
                                       'ETH',
                                       'ETH-USD Live Chart'),
        self.ognBookObject = OrderBook('ogn',
                                       'OGN-USD',
                                       'OGN',
                                       'OGN-USD Live Chart'),
        self.solBookObject = OrderBook('sol',
                                       'SOL-USD',
                                       'SOL',
                                       'SOL-USD Live Chart'),
        self.btcBookObject = OrderBook('btc',
                                       'BTC-USD',
                                       'BTC',
                                       'BTC-USD Live Chart'),
        self.compBookObject = OrderBook('comp',
                                        'COMP-USD',
                                        'COMP',
                                        'COMP-USD Live Chart'),
        self.tribeBookObject = OrderBook('tribe',
                                         'TRIBE-USD',
                                         'TRIBE',
                                         'TRIBE-USD Live Chart'),
        self.ankrBookObject = OrderBook('ankr',
                                        'ANKR-USD',
                                        'ANKR',
                                        'ANKR-USD Live Chart'),
        self.grtBookObject = OrderBook('grt',
                                       'GRT-USD',
                                       'GRT',
                                       'GRT-USD Live Chart'),
        self.filBookObject = OrderBook('fil',
                                       'FIL-USD',
                                       'FIL',
                                       'FIL-USD Live Chart'),
        self.mlnBookObject = OrderBook('mln',
                                       'MLN-USD',
                                       'MLN',
                                       'MLN-USD Live Chart'),
        self.ctsiBookObject = OrderBook('ctsi',
                                        'CTSI-USD',
                                        'CTSI',
                                        'CTSI-USD Live Chart'),
        self.raiBookObject = OrderBook('rai',
                                       'RAI-USD',
                                       'RAI',
                                       'RAI-USD Live Chart'),
        self.maskBookObject = OrderBook('mask',
                                        'MASK-USD',
                                        'MASK',
                                        'MASK-USD Live Chart'),
        self.umaBookObject = OrderBook('uma',
                                       'UMA-USD',
                                       'UMA',
                                       'UMA-USD Live Chart'),
        self.clvBookObject = OrderBook('clv',
                                       'CLV-USD',
                                       'CLV',
                                       'CLV-USD Live Chart'),
        self.ddxBookObject = OrderBook('ddx',
                                       'DDX-USD',
                                       'DDX',
                                       'DDX-USD Live Chart'),
        self.yfiiBookObject = OrderBook('yfii',
                                        'YFII-USD',
                                        'YFII',
                                        'YFII-USD Live Chart'),
        self.manaBookObject = OrderBook('mana',
                                        'MANA-USD',
                                        'MANA',
                                        'MANA-USD Live Chart'),
        self.wlunaBookObject = OrderBook('wluna',
                                         'WLUNA-USD',
                                         'WLUNA',
                                         'WLUNA-USD Live Chart'),
        self.balBookObject = OrderBook('bal',
                                       'BAL-USD',
                                       'BAL',
                                       'BAL-USD Live Chart'),
        self.etcBookObject = OrderBook('etc',
                                       'ETC-USD',
                                       'ETC',
                                       'ETC-USD Live Chart'),
        self.rlyBookObject = OrderBook('rly',
                                       'RLY-USD',
                                       'RLY',
                                       'RLY-USD Live Chart'),
        self.wbtcBookObject = OrderBook('wbtc',
                                        'WBTC-USD',
                                        'WBTC',
                                        'WBTC-USD Live Chart'),
        self.fetBookObject = OrderBook('fet',
                                       'FET-USD',
                                       'FET',
                                       'FET-USD Live Chart'),
        self.atomBookObject = OrderBook('atom',
                                        'ATOM-USD',
                                        'ATOM',
                                        'ATOM-USD Live Chart'),
        self.chzBookObject = OrderBook('chz',
                                       'CHZ-USD',
                                       'CHZ',
                                       'CHZ-USD Live Chart'),
        self.uniBookObject = OrderBook('uni',
                                       'UNI-USD',
                                       'UNI',
                                       'UNI-USD Live Chart'),
        self.ustBookObject = OrderBook('ust',
                                       'UST-USD',
                                       'UST',
                                       'UST-USD Live Chart'),
        self.achBookObject = OrderBook('ach',
                                       'ACH-USD',
                                       'ACH',
                                       'ACH-USD Live Chart'),
        self.truBookObject = OrderBook('tru',
                                       'TRU-USD',
                                       'TRU',
                                       'TRU-USD Live Chart'),
        self.cotiBookObject = OrderBook('coti',
                                        'COTI-USD',
                                        'COTI',
                                        'COTI-USD Live Chart'),
        self.iotxBookObject = OrderBook('iotx',
                                        'IOTX-USD',
                                        'IOTX',
                                        'IOTX-USD Live Chart'),
        self.bntBookObject = OrderBook('bnt',
                                       'BNT-USD',
                                       'BNT',
                                       'BNT-USD Live Chart'),
        self.aaveBookObject = OrderBook('aave',
                                        'AAVE-USD',
                                        'AAVE',
                                        'AAVE-USD Live Chart'),
        self.lrcBookObject = OrderBook('lrc',
                                       'LRC-USD',
                                       'LRC',
                                       'LRC-USD Live Chart'),
        self.dotBookObject = OrderBook('dot',
                                       'DOT-USD',
                                       'DOT',
                                       'DOT-USD Live Chart'),
        self.oxtBookObject = OrderBook('oxt',
                                       'OXT-USD',
                                       'OXT',
                                       'OXT-USD Live Chart'),
        self.xlmBookObject = OrderBook('xlm',
                                       'XLM-USD',
                                       'XLM',
                                       'XLM-USD Live Chart'),
        self.sklBookObject = OrderBook('skl',
                                       'SKL-USD',
                                       'SKL',
                                       'SKL-USD Live Chart'),
        self.ampBookObject = OrderBook('amp',
                                       'AMP-USD',
                                       'AMP',
                                       'AMP-USD Live Chart'),
        self.paxBookObject = OrderBook('pax',
                                       'PAX-USD',
                                       'PAX',
                                       'PAX-USD Live Chart'),
        self.zecBookObject = OrderBook('zec',
                                       'ZEC-USD',
                                       'ZEC',
                                       'ZEC-USD Live Chart'),
        self.trbBookObject = OrderBook('trb',
                                       'TRB-USD',
                                       'TRB',
                                       'TRB-USD Live Chart'),
        self.nknBookObject = OrderBook('nkn',
                                       'NKN-USD',
                                       'NKN',
                                       'NKN-USD Live Chart'),
        self.ornBookObject = OrderBook('orn',
                                       'ORN-USD',
                                       'ORN',
                                       'ORN-USD Live Chart'),
        self.cgldBookObject = OrderBook('cgld',
                                        'CGLD-USD',
                                        'CGLD',
                                        'CGLD-USD Live Chart'),
        self.gtcBookObject = OrderBook('gtc',
                                       'GTC-USD',
                                       'GTC',
                                       'GTC-USD Live Chart'),
        self.bandBookObject = OrderBook('band',
                                        'BAND-USD',
                                        'BAND',
                                        'BAND-USD Live Chart'),
        self.dogeBookObject = OrderBook('doge',
                                        'DOGE-USD',
                                        'DOGE',
                                        'DOGE-USD Live Chart'),
        self.icpBookObject = OrderBook('icp',
                                       'ICP-USD',
                                       'ICP',
                                       'ICP-USD Live Chart'),
        self.mkrBookObject = OrderBook('mkr',
                                       'MKR-USD',
                                       'MKR',
                                       'MKR-USD Live Chart'),
        self.enjBookObject = OrderBook('enj',
                                       'ENJ-USD',
                                       'ENJ',
                                       'ENJ-USD Live Chart'),
        self.storjBookObject = OrderBook('storj',
                                         'STORJ-USD',
                                         'STORJ',
                                         'STORJ-USD Live Chart'),
        self.usdtBookObject = OrderBook('usdt',
                                        'USDT-USD',
                                        'USDT',
                                        'USDT-USD Live Chart'),
        self.daiBookObject = OrderBook('dai',
                                       'DAI-USD',
                                       'DAI',
                                       'DAI-USD Live Chart'),
        self.renBookObject = OrderBook('ren',
                                       'REN-USD',
                                       'REN',
                                       'REN-USD Live Chart'),
        self.nmrBookObject = OrderBook('nmr',
                                       'NMR-USD',
                                       'NMR',
                                       'NMR-USD Live Chart'),
        self.ltcBookObject = OrderBook('ltc',
                                       'LTC-USD',
                                       'LTC',
                                       'LTC-USD Live Chart'),
        self.maticBookObject = OrderBook('matic',
                                         'MATIC-USD',
                                         'MATIC',
                                         'MATIC-USD Live Chart'),
        self.mirBookObject = OrderBook('mir',
                                       'MIR-USD',
                                       'MIR',
                                       'MIR-USD Live Chart'),
        self.crvBookObject = OrderBook('crv',
                                       'CRV-USD',
                                       'CRV',
                                       'CRV-USD Live Chart'),
        self.linkBookObject = OrderBook('link',
                                        'LINK-USD',
                                        'LINK',
                                        'LINK-USD Live Chart'),
        self.farmBookObject = OrderBook('farm',
                                        'FARM-USD',
                                        'FARM',
                                        'FARM-USD Live Chart'),
        self.radBookObject = OrderBook('rad',
                                       'RAD-USD',
                                       'RAD',
                                       'RAD-USD Live Chart'),
        self.omgBookObject = OrderBook('omg',
                                       'OMG-USD',
                                       'OMG',
                                       'OMG-USD Live Chart'),
        self.nuBookObject = OrderBook('nu',
                                      'NU-USD',
                                      'NU',
                                      'NU-USD Live Chart'),
        self.kncBookObject = OrderBook('knc',
                                       'KNC-USD',
                                       'KNC',
                                       'KNC-USD Live Chart'),
        self.bondBookObject = OrderBook('bond',
                                        'BOND-USD',
                                        'BOND',
                                        'BOND-USD Live Chart'),
        self.rlcBookObject = OrderBook('rlc',
                                       'RLC-USD',
                                       'RLC',
                                       'RLC-USD Live Chart'),
        self.batBookObject = OrderBook('bat',
                                       'BAT-USD',
                                       'BAT',
                                       'BAT-USD Live Chart'),
        self.algoBookObject = OrderBook('algo',
                                        'ALGO-USD',
                                        'ALGO',
                                        'ALGO-USD Live Chart'),
        self.forthBookObject = OrderBook('forth',
                                         'FORTH-USD',
                                         'FORTH',
                                         'FORTH-USD Live Chart'),
        self.plaBookObject = OrderBook('pla',
                                       'PLA-USD',
                                       'PLA',
                                       'PLA-USD Live Chart'),
        self.polyBookObject = OrderBook('poly',
                                        'POLY-USD',
                                        'POLY',
                                        'POLY-USD Live Chart'),
        self.sushiBookObject = OrderBook('sushi',
                                         'SUSHI-USD',
                                         'SUSHI',
                                         'SUSHI-USD Live Chart'),
        self.adaBookObject = OrderBook('ada',
                                       'ADA-USD',
                                       'ADA',
                                       'ADA-USD Live Chart'),
        self.keepBookObject = OrderBook('keep',
                                        'KEEP-USD',
                                        'KEEP',
                                        'KEEP-USD Live Chart'),
        self.repBookObject = OrderBook('rep',
                                       'REP-USD',
                                       'REP',
                                       'REP-USD Live Chart'),
        self.reqBookObject = OrderBook('req',
                                       'REQ-USD',
                                       'REQ',
                                       'REQ-USD Live Chart'),
        self.yfiBookObject = OrderBook('yfi',
                                       'YFI-USD',
                                       'YFI',
                                       'YFI-USD Live Chart'),
        self.bchBookObject = OrderBook('bch',
                                       'BCH-USD',
                                       'BCH',
                                       'BCH-USD Live Chart'),
        self.dashBookObject = OrderBook('dash',
                                        'DASH-USD',
                                        'DASH',
                                        'DASH-USD Live Chart'),
        self.lptBookObject = OrderBook('lpt',
                                       'LPT-USD',
                                       'LPT',
                                       'LPT-USD Live Chart'),
        self.snxBookObject = OrderBook('snx',
                                       'SNX-USD',
                                       'SNX',
                                       'SNX-USD Live Chart')

        self.dict_of_books = {
            'dai': self.daiBookObject,
            'grt': self.grtBookObject,
            'pla': self.plaBookObject,
            'ren': self.renBookObject,
            'axs': self.axsBookObject,
            'xtz': self.xtzBookObject,
            'comp': self.compBookObject,
            'rad': self.radBookObject,
            'pax': self.paxBookObject,
            'poly': self.polyBookObject,
            'keep': self.keepBookObject,
            'bch': self.bchBookObject,
            'algo': self.algoBookObject,
            'aave': self.aaveBookObject,
            'qnt': self.qntBookObject,
            'bat': self.batBookObject,
            'usdt': self.usdtBookObject,
            'mana': self.manaBookObject,
            'dash': self.dashBookObject,
            'zec': self.zecBookObject,
            'orn': self.ornBookObject,
            'rep': self.repBookObject,
            'enj': self.enjBookObject,
            'storj': self.storjBookObject,
            'bnt': self.bntBookObject,
            'mir': self.mirBookObject,
            'quick': self.quickBookObject,
            'matic': self.maticBookObject,
            'sol': self.solBookObject,
            'req': self.reqBookObject,
            'eos': self.eosBookObject,
            'nmr': self.nmrBookObject,
            'snx': self.snxBookObject,
            'knc': self.kncBookObject,
            'rai': self.raiBookObject,
            'yfi': self.yfiBookObject,
            'mln': self.mlnBookObject,
            'farm': self.farmBookObject,
            'bond': self.bondBookObject,
            'mask': self.maskBookObject,
            'coti': self.cotiBookObject,
            'mkr': self.mkrBookObject,
            'fet': self.fetBookObject,
            'rlc': self.rlcBookObject,
            'omg': self.omgBookObject,
            'uni': self.uniBookObject,
            'crv': self.crvBookObject,
            'rly': self.rlyBookObject,
            'skl': self.sklBookObject,
            'eth': self.ethBookObject,
            'ankr': self.ankrBookObject,
            'ust': self.ustBookObject,
            'dot': self.dotBookObject,
            'lrc': self.lrcBookObject,
            'uma': self.umaBookObject,
            'yfii': self.yfiiBookObject,
            'ogn': self.ognBookObject,
            'xlm': self.xlmBookObject,
            'clv': self.clvBookObject,
            'bal': self.balBookObject,
            'wluna': self.wlunaBookObject,
            'wbtc': self.wbtcBookObject,
            'tru': self.truBookObject,
            'forth': self.forthBookObject,
            'cgld': self.cgldBookObject,
            'ddx': self.ddxBookObject,
            'ach': self.achBookObject,
            'icp': self.icpBookObject,
            'amp': self.ampBookObject,
            'sushi': self.sushiBookObject,
            'band': self.bandBookObject,
            'trb': self.trbBookObject,
            'ada': self.adaBookObject,
            'iotx': self.iotxBookObject,
            'nkn': self.nknBookObject,
            'etc': self.etcBookObject,
            'tribe': self.tribeBookObject,
            'gtc': self.gtcBookObject,
            'doge': self.dogeBookObject,
            '1inch': self.inchBookObject,
            'link': self.linkBookObject,
            'ltc': self.ltcBookObject,
            'btc': self.btcBookObject,
            'oxt': self.oxtBookObject,
            'lpt': self.lptBookObject,
            'fil': self.filBookObject,
            'atom': self.atomBookObject,
            'chz': self.chzBookObject,
            'ctsi': self.ctsiBookObject,
            'nu': self.nuBookObject,
            'zrx': self.zrxBookObject,
        }

    def get_books(self, book):
        if book in self.dict_of_books:
            return self.dict_of_books.get(book)
